name: "Cypress"
description: "Run a set of cypress tests"

inputs:
  version:
    description: "Version of cypress to use"
    required: true
    default: 4.12.0
  test:
    description: "Name of test folder"
    required: false
  site:
    description: "Name of site folder"
    required: false
  base_url:
    description: "Base url"
    required: false
  ref_url:
    description: "Ref url"
    required: false

runs:
  using: docker
  image: Dockerfile
  env:
    CYPRESS_VERSION: "${{ inputs.version }}"
  args:
    - "${{ inputs.test }}"
    - "${{ inputs.site }}"
    - "${{ inputs.base_url }}"
    - "${{ inputs.ref_url }}"
