name: "Add URL to Pull request"
description: "Add environment url to pull request description"

inputs:
  url:
    description: "URL of Devcloud environment"
    required: true
  caption:
    description: "Override caption for the link"
    required: false
  fetch:
    description: Whether to force PR body fetched via API
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Get associated pull request
      if: ${{ github.event_name == 'push' }}
      uses: jwalton/gh-find-current-pr@v1
      id: findPr
    - name: Add environment link to pull request comment
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      uses: actions/github-script@v6
      with:
        script: |
          let now = new Date();
          console.log(now.toUTCString());
          console.log(context.payload)
          let caption = '${{ inputs.caption }}'
          if (! caption) {
            caption = 'View environment ${{ inputs.url }}'
          }
          const snippet = `<h3><a href="https://${{ inputs.url }}">:arrow_forward:&nbsp;&nbsp;${caption}</a></h3>`
          const owner = context.payload.repository.owner.login
          const repo = context.payload.repository.name
          let fetch_body = '${{ inputs.fetch }}'

          let pr;
          let body;

          if (context.payload.pull_request) {
            pr = context.payload.pull_request.number
            body = context.payload.pull_request.body
          }
          else {
            pr = '${{ steps.findPr.outputs.number }}'
            fetch_body = 'true'
          }

          if (pr) {
            if (fetch_body === 'true') {
              console.log(`Fetching description from PR ${pr}`);
              if (pr) {
                const data = await github
                  .request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
                    owner,
                    repo,
                    pull_number: pr,
                  })
                  .then(({ data }) => data)

                body = data.body;
              }
            }
            else {
              console.log(`Updating description from PR ${pr}`);
            }

            let updatedBody;

            console.log(`Body being processed:`);
            console.log(body);
            if (body) {
              if (body.includes(snippet)) {
                console.log('Description already includes deployed url');
                return 0;
              }
              console.log(`Adding link to existing body`);
              updatedBody = `${body} \n\n ${snippet}`;
            }
            else {
              console.log(`Adding link to empty body`);
              updatedBody = `${snippet}`;
            }

            console.log(`Body being written to PR:`);
            console.log(updatedBody);
            const updateResponse = await github
              .request('PATCH /repos/{owner}/{repo}/pulls/{pull_number}', {
                owner,
                repo,
                pull_number: pr,
                body: updatedBody,
              })

            if (!updateResponse) {
              console.log(`Error while updating PR ${pr}`);
              return 1;
            }
          }
