name: Reset Workspace Ownership Action
description: A GitHub Action to reset ownership of the files not owned by the Actions runner in the workspace directory

inputs:
  user_id:
    description: The user id to change the owner to when not matched
    required: true

  workspace_path:
    description: The path to the workspace to process
    required: true
    default: ${{ github.workspace }}

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.user_id }}
    - ${{ inputs.workspace_path }}

branding:
  icon: user-check
  color: yellow
