name: 'Drupal Security Update'
description: 'Automatically update Composer dependencies with security vulnerabilities'
author: 'Phase2'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: true
  github_token:
    description: 'GitHub token for creating branches and PRs (defaults to github.token)'
    required: false
    default: ${{ github.token }}
  working_directory:
    description: 'Directory containing composer.json'
    required: false
    default: '.'
  base_branch:
    description: 'Base branch for the PR'
    required: false
    default: 'main'
  dry_run:
    description: 'If true, check for vulnerabilities but do not create PR'
    required: false
    default: 'false'
  branch_prefix:
    description: 'Prefix for the created branch name (e.g., "issue/" creates "issue/autoupdate-YYYYMMDDHHMM")'
    required: false
    default: 'issue/'
  pr_reviewers:
    description: 'Comma-separated list of GitHub usernames to request review from on the created PR'
    required: false
    default: ''
  pr_label:
    description: 'Label applied to PRs for deduplication. Set to empty string to disable labeling.'
    required: false
    default: 'drupal-security-update'
  deduplicate_prs:
    description: 'If true, close existing open PRs with the same label before creating a new one'
    required: false
    default: 'true'
  slack_bot_token:
    description: 'Slack bot OAuth token for posting notifications (requires slack_channel_id)'
    required: false
    default: ''
  slack_channel_id:
    description: 'Slack channel ID to post notification when PR is created (requires slack_bot_token)'
    required: false
    default: ''
  slack_errors:
    description: 'If true, fail the workflow when Slack notification fails'
    required: false
    default: 'false'

outputs:
  has_vulnerabilities:
    description: 'Whether security vulnerabilities were found'
    value: ${{ steps.audit.outputs.has_vulnerabilities }}
  pr_url:
    description: 'URL of the created pull request (if any)'
    value: ${{ steps.create-pr.outputs.pull-request-url }}
  vulnerabilities_found:
    description: 'Number of vulnerabilities found'
    value: ${{ steps.audit.outputs.vulnerability_count }}
  pr_action:
    description: 'Action taken for PR (create, supersede)'
    value: ${{ steps.existing-pr.outputs.action || 'create' }}
  superseded_pr:
    description: 'PR number(s) that were superseded (comma-separated if multiple)'
    value: ${{ steps.existing-pr.outputs.superseded_prs }}

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if [ -f composer.lock ]; then
          composer install --no-interaction --no-progress
        fi

    - name: Run Composer audit
      id: audit
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set +e
        AUDIT_OUTPUT=$(composer audit --format=json 2>/dev/null)
        AUDIT_EXIT_CODE=$?
        set -e

        echo "audit_json<<GHAAJEOF" >> $GITHUB_OUTPUT
        echo "$AUDIT_OUTPUT" >> $GITHUB_OUTPUT
        echo "GHAAJEOF" >> $GITHUB_OUTPUT

        if [ $AUDIT_EXIT_CODE -ne 0 ]; then
          VULN_COUNT=$(echo "$AUDIT_OUTPUT" | jq -r '.advisories | to_entries | map(.value | length) | add // 0')
          echo "has_vulnerabilities=true" >> $GITHUB_OUTPUT
          echo "vulnerability_count=$VULN_COUNT" >> $GITHUB_OUTPUT
          echo "::warning::Found $VULN_COUNT security vulnerabilities in Composer dependencies"
        else
          echo "has_vulnerabilities=false" >> $GITHUB_OUTPUT
          echo "vulnerability_count=0" >> $GITHUB_OUTPUT
          echo "::notice::No security vulnerabilities found"
        fi

    - name: Stop if no vulnerabilities found or this is a dry run
      if: steps.audit.outputs.has_vulnerabilities != 'true' || inputs.dry_run == 'true'
      shell: bash
      run: |
        if [ "${{ steps.audit.outputs.has_vulnerabilities }}" != "true" ]; then
          echo "No security vulnerabilities found. Exiting."
        else
          echo "Dry run mode - vulnerabilities found but not creating PR."
          echo "Vulnerabilities: ${{ steps.audit.outputs.vulnerability_count }}"
        fi

    - name: Resolve action path and ensure instructions are there
      id: action-path
      if: steps.audit.outputs.has_vulnerabilities == 'true' && inputs.dry_run != 'true'
      shell: bash
      run: |
        INSTRUCTIONS_PATH="$GITHUB_ACTION_PATH/instructions.md"
        if [ ! -f "$INSTRUCTIONS_PATH" ]; then
          echo "::error::instructions.md not found at $INSTRUCTIONS_PATH"
          exit 1
        fi
        echo "path=$GITHUB_ACTION_PATH" >> $GITHUB_OUTPUT

    - name: Run Claude Code for updates
      if: steps.audit.outputs.has_vulnerabilities == 'true' && inputs.dry_run != 'true'
      uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        github_token: ${{ inputs.github_token }}
        show_full_output: true
        claude_args: |
          --allowedTools "Bash,Read,Write,Edit,Glob,Grep,WebFetch,WebSearch"
        prompt: |
          Perform a Drupal security update based on composer audit results.

          Read the instructions at ${{ steps.action-path.outputs.path }}/instructions.md and follow them precisely.
          If you can not find the instructions at the specified path, do not proceed or search for them at an alternate location.

          The composer audit found the following vulnerabilities:
          ```json
          ${{ steps.audit.outputs.audit_json }}
          ```

          Working directory: ${{ inputs.working_directory }}

          Key requirements:
          - Run validation before completing
          - Create pr_body.md with security advisory links and any patch changes
          - Create commit_message.txt with a concise commit message summarizing the updates
          - Document any transitive vulnerabilities that require upstream fixes
          - DO NOT stage or commit changes

    - name: Prepare PR metadata
      if: steps.audit.outputs.has_vulnerabilities == 'true' && inputs.dry_run != 'true'
      id: prepare-pr
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        # Generate branch name with prefix
        BRANCH_NAME="${{ inputs.branch_prefix }}autoupdate-$(date +%Y%m%d%H%M)"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

        # Generate PR title with date
        PR_TITLE="Security: Drupal security updates - $(date +%Y-%m-%d)"
        echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT

        # Read PR body from Claude's output (if exists) then remove it so it's not committed
        if [ -f pr_body.md ]; then
          {
            echo "pr_body<<GHPREOF"
            cat pr_body.md
            echo "GHPREOF"
          } >> $GITHUB_OUTPUT
          rm pr_body.md
        else
          {
            echo "pr_body<<GHPREOF"
            echo "Automated security update for Drupal Composer dependencies."
            echo ""
            echo "This PR addresses ${{ steps.audit.outputs.vulnerability_count }} security vulnerabilities found by \`composer audit\`."
            echo "GHPREOF"
          } >> $GITHUB_OUTPUT
        fi

        # Read commit message from Claude's output (if exists) then remove it so it's not committed
        if [ -f commit_message.txt ]; then
          {
            echo "commit_message<<GHCMEOF"
            cat commit_message.txt
            echo "GHCMEOF"
          } >> $GITHUB_OUTPUT
          rm commit_message.txt
        else
          {
            echo "commit_message<<GHCMEOF"
            echo "Security update: Drupal Composer dependencies"
            echo ""
            echo "Automated security update performed by Drupal Security Updates action."
            echo "Vulnerabilities addressed: ${{ steps.audit.outputs.vulnerability_count }}"
            echo "GHCMEOF"
          } >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.audit.outputs.has_vulnerabilities == 'true' && inputs.dry_run != 'true'
      id: create-pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.github_token }}
        branch: ${{ steps.prepare-pr.outputs.branch_name }}
        base: ${{ inputs.base_branch }}
        title: ${{ steps.prepare-pr.outputs.pr_title }}
        body: ${{ steps.prepare-pr.outputs.pr_body }}
        commit-message: ${{ steps.prepare-pr.outputs.commit_message }}
        reviewers: ${{ inputs.pr_reviewers }}
        labels: ${{ inputs.pr_label }}
        committer: drupal-security-update[bot] <drupal-security-update@users.noreply.github.com>
        author: drupal-security-update[bot] <drupal-security-update@users.noreply.github.com>

    - name: Close existing security PRs
      if: steps.create-pr.outputs.pull-request-url != '' && inputs.deduplicate_prs == 'true' && inputs.pr_label != ''
      id: existing-pr
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          // Find open PRs with the security label on the target base branch
          const prs = await github.paginate(github.rest.pulls.list, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            base: '${{ inputs.base_branch }}',
            per_page: 100
          });

          // Filter to PRs with the matching label, excluding the just-created PR
          const newPrNumber = parseInt('${{ steps.create-pr.outputs.pull-request-number }}', 10);
          const securityPRs = prs.filter(pr =>
            pr.number !== newPrNumber &&
            pr.labels.some(l => l.name === '${{ inputs.pr_label }}')
          );

          if (securityPRs.length === 0) {
            core.info('No existing security PRs found');
            core.setOutput('action', 'create');
            return;
          }

          // Close each existing security PR with a comment
          const closedPRs = [];
          for (const pr of securityPRs) {
            // Skip PRs from forks
            if (pr.head.repo?.full_name !== '${{ github.repository }}') {
              core.info(`Skipping fork PR #${pr.number}`);
              continue;
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `This PR has been superseded by a newer security update. Closing in favor of #${newPrNumber}.`
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              state: 'closed'
            });

            // Delete the branch associated with the closed PR (best-effort)
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${pr.head.ref}`
              });
            } catch (err) {
              core.warning(`Could not delete branch ${pr.head.ref}: ${err.message}`);
            }

            core.notice(`Closed superseded PR #${pr.number} and deleted branch ${pr.head.ref}`);
            closedPRs.push(pr.number);
          }

          core.setOutput('action', 'supersede');
          core.setOutput('superseded_prs', closedPRs.join(','));

    - name: Report PR status
      if: steps.audit.outputs.has_vulnerabilities == 'true' && inputs.dry_run != 'true'
      shell: bash
      run: |
        if [ -n "${{ steps.create-pr.outputs.pull-request-url }}" ]; then
          echo "::notice::Created PR: ${{ steps.create-pr.outputs.pull-request-url }}"
        else
          echo "::warning::Vulnerabilities found but no changes were made (packages may already be at latest versions)"
        fi

    - name: Post Slack notification for PR
      if: steps.create-pr.outputs.pull-request-url != '' && inputs.slack_channel_id != '' && inputs.slack_bot_token != ''
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        errors: ${{ inputs.slack_errors }}
        payload: |
          channel: ${{ inputs.slack_channel_id }}
          text: "Drupal Security Update: ${{ steps.audit.outputs.vulnerability_count }} vulnerabilities found in ${{ github.repository }}. Review PR: ${{ steps.create-pr.outputs.pull-request-url }}"
          blocks:
            - type: header
              text:
                type: plain_text
                text: ":shield: Drupal Security Update Required"
            - type: section
              text:
                type: mrkdwn
                text: "A new security update PR has been created for *${{ github.repository }}*."
            - type: section
              fields:
                - type: mrkdwn
                  text: "*Action Required:*\n<${{ steps.create-pr.outputs.pull-request-url }}|Review and merge PR>"
                - type: mrkdwn
                  text: "*Vulnerabilities Found:*\n${{ steps.audit.outputs.vulnerability_count }}"

    - name: Post Slack notification for unresolvable vulnerabilities
      if: steps.audit.outputs.has_vulnerabilities == 'true' && inputs.dry_run != 'true' && steps.create-pr.outputs.pull-request-url == '' && inputs.slack_channel_id != '' && inputs.slack_bot_token != ''
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        errors: ${{ inputs.slack_errors }}
        payload: |
          channel: ${{ inputs.slack_channel_id }}
          text: "Drupal Security Update: ${{ steps.audit.outputs.vulnerability_count }} vulnerabilities found in ${{ github.repository }} but could not be automatically resolved. Manual intervention required."
          blocks:
            - type: header
              text:
                type: plain_text
                text: ":warning: Drupal Security Update - Manual Action Required"
            - type: section
              text:
                type: mrkdwn
                text: "Security vulnerabilities were detected in *${{ github.repository }}* but could not be automatically resolved."
            - type: section
              fields:
                - type: mrkdwn
                  text: "*Action Required:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Review workflow run for details and manually update>"
                - type: mrkdwn
                  text: "*Vulnerabilities Found:*\n${{ steps.audit.outputs.vulnerability_count }}"
