name: 'Test add-pr-url'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - issue/**

defaults:
  run:
    shell: bash

jobs:

  changes:
    name: Detect file changes
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      action: ${{ steps.filter.outputs.action }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Find file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.event.before }}
          filters: |
            action:
              - 'actions/add-pr-url/**'
  test:
    name: Test add-pr-url
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.action == 'true' }}
    steps:
      # Steps run at the beginning of each job.
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Add url link to PR
        uses: phase2/octane-actions/actions/add-pr-url@${{ github.ref_name }}
        with:
          url: www.example.com
          caption: Test Link
