name: 'Test Actions'

on:
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash

jobs:

  changes:
    name: Detect file changes
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      add-pr-url: ${{ steps.filter.outputs.add-pr-url }}
      load-env: ${{ steps.filter.outputs.load-env }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Find file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.event.before }}
          filters: |
            add-pr-url:
              - 'actions/add-pr-url/**'
            load-env:
              - 'actions/load-env/**'

  test-add-pr-url:
    name: Test add-pr-url
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.add-pr-url == 'true' }}
    steps:
      - name: Add url link to PR
        uses: phase2/octane-actions/actions/add-pr-url@develop
        with:
          url: www.example.com
          caption: Test Link

  test-load-env:
    name: Test load-env
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.load-env == 'true' }}
    steps:
      - name: Load environment
        uses: phase2/octane-actions/actions/load-env@develop
      - name: Get results
        run: |
          if [ "$PROJECT_NAME" != "octane-actions" ]; then
            echo "ERROR loading .env file"
            exit 1
          fi
          if [ "$CI_URL" != "devcloud.fayze2.com" ]; then
            echo "ERROR setting CI_URL"
            exit 1
          fi
          if [ "$CI_BRANCH" != "develop" ]; then
            echo "ERROR setting CI_BRANCH"
            exit 1
          fi
