name: 'Test Actions'

on:
  push:
    branches:
      - develop

defaults:
  run:
    shell: bash

jobs:

  changes:
    name: Detect file changes
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      add-pr-url: ${{ steps.filter.outputs.add-pr-url }}
      load-env: ${{ steps.filter.outputs.load-env }}
      cypress: ${{ steps.filter.outputs.cypress }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Find file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.event.before }}
          filters: |
            add-pr-url:
              - 'actions/add-pr-url/**'
              - '.github/workflows/test.yml'
            load-env:
              - 'actions/load-env/**'
              - '.github/workflows/test.yml'
            cypress:
              - 'actions/cypress/**'
              - '.github/workflows/test.yml'

  test-add-pr-url:
    name: Test add-pr-url
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.add-pr-url == 'true' }}
    steps:
      - name: Add url link to PR
        uses: phase2/octane-actions/actions/add-pr-url@develop
        with:
          url: www.example.com
          caption: Test Link

  test-load-env:
    name: Test load-env
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.load-env == 'true' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Load environment
        uses: phase2/octane-actions/actions/load-env@develop
      - name: Environment vars
        run: env
      - name: Validate results
        run: |
          result=0
          echo "PROJECT_NAME: $PROJECT_NAME"
          if [ "$PROJECT_NAME" != "octane-actions" ]; then
            echo "ERROR loading .env file"
            result=1
          fi
          echo "CI_URL: $CI_URL"
          if [ "$CI_URL" != "devcloud.fayze2.com" ]; then
            echo "ERROR setting CI_URL"
            result=1
          fi
          echo "CI_BRANCH: $CI_BRANCH"
          if [ "$CI_BRANCH" != "develop" ]; then
            echo "ERROR setting CI_BRANCH"
            result=1
          fi
          if [[ ! -z $(which npm 2>/dev/null || echo "") ]]; then
            npmConfig=$(npm config get prefix)
            echo "npm config get prefix: $npmConfig"
            if [ "$npmConfig" != "/home/runner/work/octane-actions/octane-actions/.config/npm/global" ]; then
              echo "ERROR setting npm config"
              result=1
            fi
          fi
          exit $result

  test-cypress:
    name: Test Cypress
    runs-on: ubuntu-latest
    needs: [changes]
    if: ${{ needs.changes.outputs.cypress == 'true' }}
    steps:
      - name: Run Cypress
        uses: phase2/octane-actions/actions/cypress@develop
        with:
          version: 4.12.0
          test: mytest
          site: mysite
          base_url: mybase
          ref_url: myref
